### ISSUE TITLE
Cannot find config module

### ISSUE THREAD

**Issue by ghost** [kushsolitary/Inkpen#1]
I know how to include it, but can you document what should a standard config file include?

Error: Cannot find module '../../config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/users/sergiuvariu/work/24biz/Inkpen/app/routes/oauth.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by kushsolitary** [comment]
Fixed in eb51ca41d99f29cebf5870f6c475a7cd030147ba
Please check out the new readme file for more instructions.
